### ISSUE TITLE
Using alternative S3 compatible storage?

### ISSUE THREAD

**Issue by kulshekhar** [facebookgo/rocks-strata#15]
Is it possible to use S3 alternatives like [minio](https://github.com/minio/minio) with Strata?

**Comment by igorcanadi** [comment]
Yes, definitely. Strata was written with a goal to be modular with respect to database (mongorocks or any other rocksdb-based database) and storage. You will only need to copy the S3 implementation (all in one file https://github.com/facebookgo/rocks-strata/blob/master/strata/s3storage/storage.go) and replace S3 calls with minio calls. We're happy to take the contribution from you.

**Comment by kulshekhar** [comment]
I took a look at the source code and I'm not quite sure where to start. Should I look to create a package parallel to the `s3storage` package?

**Comment by igorcanadi** [comment]
Yup!
