### ISSUE TITLE
Can backups be initiated from a remote server?

### ISSUE THREAD

**Issue by asdf01** [facebookgo/rocks-strata#23]
Hey Guys

Can the strata backup process be initiated from a remote server or does it need direct file system access as well as the mongo shell access credentials?  

I tried initiating the strata backup process from somewhere else on the internet.  Initially it didn't work as strata only connects to localhost.  But after I setup a reverse proxy to redirect traffic from localhost to my mongodb on the internet, it failed with some other error.  I'm guessing the strata process needs direct file system access is that right?  

Thanks

**Comment by AGFeldman** [comment]
`strata backup` accesses the local filesystem to perform a backup, so it needs to run on the same machine that runs the database. You can still invoke it remotely, but you'd need to do something like http://stackoverflow.com/questions/305035/how-to-use-ssh-to-run-shell-script-on-a-remote-machine.

**Comment by asdf01** [comment]
Hi AGFeldman.  Thanks for your help on this issue.
