### ISSUE TITLE
Using strata with user and password

### ISSUE THREAD

**Issue by arturogutierrez** [facebookgo/rocks-strata#5]
I'm preparing my environment to migrate my parse data to my own machines. Strata was working fine until I enabled the authentication in my mongodb. Since then, strata could connect to mongodb (obviously):

```2016/03/28 12:54:07 Getting dbpath
not authorized on admin to execute command { getCmdLineOpts: 1 }```

Now, I don't know how to pass some credentials to strata and I don't want to expose my mongodb to Internet without authorization. I'm very noob with mongodb but, can anyone help me bring some light in this?

Thanks in advance

**Comment by igorcanadi** [comment]
@arturogutierrez we don't yet support auth (since we run mongodb inside of a private network), but shouldn't be hard to add, we'll try to do it today or tomorrow!

**Comment by arturogutierrez** [comment]
Great news! and very fast! Looking forward to seeing the commit! :smiley:

**Comment by tredman** [comment]
Submitted https://github.com/facebookgo/rocks-strata/pull/7 for review.

**Comment by igorcanadi** [comment]
@arturogutierrez can you try if the auth works for you now?

**Comment by tredman** [comment]
This section of the docs should get you going with the right user permissions: https://github.com/facebookgo/rocks-strata#using-password-auth

**Comment by arturogutierrez** [comment]
Tested and working like a charm! :clap:

**Comment by igorcanadi** [comment]
Awesome!
