### ISSUE TITLE
Querying backups support removed?

### ISSUE THREAD

**Issue by arturogutierrez** [facebookgo/rocks-strata#9]
Hi again!

The docs says that you can query your backups in S3 running `./strata --bucket=all_backups --bucket-prefix=mongo-rocks show backups --replica-id=one-off-test`:
```
ID   data                      num files   size (GB)   incremental files   incremental size   duration
0    2015-09-02 21:11:20 UTC   4           0.000005    4                   0.000005           187.929573ms
```
But if you run it you get something like `2016/03/29 14:40:19 Starting strata driver unknown flag 'r'`

The command `show backups` seems removed, if you do a `strata show --help` you get:
```
Available commands:
  last-backup-time  seconds since epoch
  replica-ids       show replica ids
```

My question is, has the command `show backups` been removed? and can we query the backups only with the `mongoq` extended shell? 

The funny thing is I realized this when I was trying to restore a backup (testing it in order to get familiar with the process) trying to know the backup-id with this command.

Thanks again.

**Comment by tredman** [comment]
Hi @arturogutierrez "show backups" should work. Can you post the exact command you are using (can obfuscate any exact values you need to)? With the go-flags library, I've noticed that the order of arguments sometimes matters - this could be related to that. I will try to reproduce it.

**Comment by arturogutierrez** [comment]
I've tested with `strata -b=my-bucket -p=my-prefix show backups -r=my-replica` and `strata -b=my-bucket -p=my-prefix -r=my-replica show backups` with no luck

**Comment by tredman** [comment]
Ah, indeed the go-flags library was discarding "show backups" from the CLI completely. I've submitted a fix: https://github.com/facebookgo/rocks-strata/pull/10

**Comment by arturogutierrez** [comment]
That explains :).
BTW, updated, tested and it's working :+1: 

Thanks!
